upload the project
G-Ro-Man/Front-end_School_HW_1 pull request #1
Opened 2021-12-23 15:16 UTC by G-Ro-Man

2021-12-27 12:35 UTC, meteofix requested changes
В целом приложение написано хорошо. Добавил несколько комментариев с предложениями и замечаниями.
Основное замечание: index.tsx - плохой выбор имен для файлов компонентов. Из имен файлов совсем не очевидно, что внутри. Это очень усложняет инспектирование и в целом навигацию по структуре приложения. Рекомендую называть файлы так же, как и компоненты внутри них.

2021-12-27 12:35 UTC, meteofix commented on src/App.css
> +}
Насколько я понимаю, эти стили остались от изначального шаблона cra и не используются в проекте. Их стоит удалить. Возможно, как и другие неиспользуемые файлы.

2021-12-27 12:35 UTC, meteofix commented on src/App.tsx
> +    <>
AppRouter здесь единственный элемент, скобки фрагмента излишни. К тому же, возможно излишня и сама функция, так как она сама по себе ничего не выполняет (разве что чтобы не нарушать структуру, где базовый компонент называется App).

2021-12-27 12:35 UTC, meteofix commented on src/features/trending-feed/components/trending-post/index.tsx
> +}: PostProps) => {
Деструктуризация пропсов - хорошо, но передавать их лучше одним объектом, а не по отдельности

2021-12-27 12:35 UTC, meteofix commented on src/features/trending-feed/index.tsx
> +    />
Слишком много пропсов, принадлежащих одной структуре, передается отдельно. С другой стороны, если передавать post, передастся много лишней информации. Может, объединить нужное в отдельный объект?

2021-12-27 12:35 UTC, meteofix commented on src/features/trending-feed/index.tsx
> +    />
Хотя я не до конца уверен, что эта рекомендация, подходящая для обычных функций, в такой же мере актуальна в данном случае для компонентов c именной передачей пропсов.

2021-12-27 12:35 UTC, meteofix commented on src/features/user-profile/index.tsx
> +              {userInfo.user.verified ? 'verified' : null}
Не уверен в правильности использования здесь null.

2021-12-27 12:35 UTC, meteofix commented on src/features/user-profile/index.tsx
> +        </li>
Можно выделить повторяющиеся части в отдельный компонент

2021-12-27 12:35 UTC, meteofix commented on src/utils/fetch-data.ts
> +          'x-rapidapi-host': 'tiktok33.p.rapidapi.com',
Лучше вынести конфиги (в том числе url-ы) константами в отдельный файл, не хардкодить. Это позволит облегчить чтение кода и изменение конфигов при необходимости

2021-12-27 12:35 UTC, meteofix commented on src/utils/fetch-data.ts
> +    console.error('err: ', err);
Рекомендуется использовать название error вместо err

2021-12-27 12:35 UTC, meteofix commented on src/utils/fetch-data.ts
> +export const getUserFeed = async (name: string) => {
getUserFeed  отличается от getUserInfo и getTrendingFeed только url-ом, стоит переписать все три как одну функцию с аргументом url.

2021-12-27 12:35 UTC, meteofix commented on src/utils/minimize-number.ts
> +const THOUSAND = 1_000;
Для чисел с четырьмя цифрами разделитель можно не использовать

2021-12-27 12:35 UTC, meteofix commented on src/utils/minimize-number.ts
> +  if (number >= 1000000) {
А вот здесь наоборот, стоит использовать разделитель) А точнее, заменить на определенную ранее константу MILLION

2021-12-27 12:35 UTC, meteofix commented on .eslintrc.json
> +  ],
К проекту не подключен prettier. Конечно, можно использовать линтер для оформления кода, и как по мне, в кое в чем такой вариант даже лучше, но подключение prettier было в дз.

2021-12-27 12:35 UTC, meteofix commented on src/features/trending-feed/index.tsx
> +    async function anyNameFunction() {
Из имени функции непонятно, что она делает

2021-12-27 12:35 UTC, meteofix commented on src/features/user-profile/index.tsx
> +      </Container>
Используется в нескольких местах - рекомендую выделить отдельным компонентом.

2021-12-27 12:35 UTC, meteofix commented on src/features/user-profile/index.tsx
> +    async function anyNameFunction() {
Из имени функции непонятно, что она делает

2021-12-27 12:35 UTC, meteofix commented on src/features/user-profile/index.tsx
> +  const userFeed = mochUserFeed;
Рекомендую хранить данные в файле формат .json вместо того, чтобы хардкодить их в компонент mochUserFeed в файл .ts.

2021-12-27 12:35 UTC, meteofix commented on src/utils/minimize-number.ts
> +};
Также стоит написать похожий функционал для биллиона, ведь числа такого размера так же встречаются в тикток.

2021-12-30 13:31 UTC, G-Ro-Man commented on src/features/trending-feed/index.tsx
> +    async function anyNameFunction() {
ok

2021-12-30 13:42 UTC, G-Ro-Man commented on src/features/user-profile/index.tsx
> +      </Container>
ok

2021-12-30 13:55 UTC, G-Ro-Man commented on src/features/user-profile/index.tsx
> +  const userFeed = mochUserFeed;
пока оставлю так, сейчас это будет трудозатратно переделать, в будущем учту, спасибо

2021-12-30 13:56 UTC, G-Ro-Man commented on src/features/user-profile/index.tsx
> +              {userInfo.user.verified ? 'verified' : null}
нулл возвращет ничего, но ок поправлю

2021-12-30 14:03 UTC, G-Ro-Man commented on src/utils/minimize-number.ts
> +  if (number >= 1000000) {
то случайно оставил в таком виде )

2021-12-30 14:04 UTC, G-Ro-Man commented on src/App.tsx
> +    <>
ок

2021-12-30 14:06 UTC, G-Ro-Man commented on src/App.css
> +}
ok

2021-12-30 22:29 UTC, yskopenko reviewed
Проделана хорошая работа, но стоит подключить prettier для финального результата!
Ты - молодец, продолжай в том же духе.)

2021-12-31 17:35 UTC, G-Ro-Man commented on src/features/user-profile/index.tsx
> +        </li>
yeap

2021-12-31 17:51 UTC, G-Ro-Man commented on src/utils/fetch-data.ts
> +          'x-rapidapi-host': 'tiktok33.p.rapidapi.com',
сделал константи

2021-12-31 17:54 UTC, G-Ro-Man commented on src/utils/fetch-data.ts
> +export const getUserFeed = async (name: string) => {
я не согласен, я думаю это убьет читаемость кода, плюс лишний импорт в компонентах

2021-12-31 17:58 UTC, G-Ro-Man commented on src/features/trending-feed/index.tsx
> +    />
спасибо, учту

2021-12-31 18:00 UTC, G-Ro-Man commented on .eslintrc.json
> +  ],
у меня подключен притиер глобально, спасибо, учту в дальнейшем

2022-01-15 23:15 UTC, merged